name: Release Build

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
        ./gradlew assembleRelease
        ./gradlew bundleRelease

    - uses: r0adkll/sign-android-release@v1
      name: Sign app Google APK
      id: sign_apk_google
      with:
        releaseDirectory: app/build/outputs/apk/google/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

    - uses: r0adkll/sign-android-release@v1
      name: Sign app FOSS APK
      id: sign_apk_foss
      with:
        releaseDirectory: app/build/outputs/apk/foss/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

    - uses: r0adkll/sign-android-release@v1
      name: Sign app bundle (Google)
      id: sign_bundle_google
      with:
        releaseDirectory: app/build/outputs/bundle/googleRelease
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}
    
    - uses: r0adkll/sign-android-release@v1
      name: Sign app bundle (FOSS)
      id: sign_bundle_foss
      with:
        releaseDirectory: app/build/outputs/bundle/fossRelease
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

    - name: Upload a Build Artifact (APK)
      uses: actions/upload-artifact@v3.0.0
      with:
        name: signedAPK
        path: |
          ${{steps.sign_apk_google.outputs.signedReleaseFile}}
          ${{steps.sign_apk_foss.outputs.signedReleaseFile}}

    - name: Upload a Build Artifact (Bundle)
      uses: actions/upload-artifact@v3.0.0
      with:
        name: signedBundle
        path: |
          ${{steps.sign_bundle_google.outputs.signedReleaseFile}}
          ${{steps.sign_bundle_foss.outputs.signedReleaseFile}}
    
    - name: Compute MD5 hashes for Build Artifact
      run: |
        md5sum ${{steps.sign_apk_google.outputs.signedReleaseFile}} | awk '{ print $1 }' > ${{steps.sign_apk_google.outputs.signedReleaseFile}}.md5
        md5sum ${{steps.sign_apk_foss.outputs.signedReleaseFile}} | awk '{ print $1 }' > ${{steps.sign_apk_foss.outputs.signedReleaseFile}}.md5
        md5sum ${{steps.sign_bundle_google.outputs.signedReleaseFile}} | awk '{ print $1 }' > ${{steps.sign_bundle_google.outputs.signedReleaseFile}}.md5
        md5sum ${{steps.sign_bundle_foss.outputs.signedReleaseFile}} | awk '{ print $1 }' > ${{steps.sign_bundle_foss.outputs.signedReleaseFile}}.md5

    - name: Upload installer to release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{steps.sign_apk_google.outputs.signedReleaseFile}}
          ${{steps.sign_apk_foss.outputs.signedReleaseFile}}.md5
          ${{steps.sign_bundle_google.outputs.signedReleaseFile}}
          ${{steps.sign_bundle_foss.outputs.signedReleaseFile}}.md5
