name: Release Build

on:
  release:
    types: [published]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
        ./gradlew assembleRelease
        ./gradlew bundleRelease
        mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release.apk

    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      id: sign_apk
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

    - uses: r0adkll/sign-android-release@v1
      name: Sign app bundle
      id: sign_bundle
      with:
        releaseDirectory: app/build/outputs/bundle/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

    - name: Upload a Build Artifact (APK)
      uses: actions/upload-artifact@v3.0.0
      with:
        name: signedAPK
        path: ${{steps.sign_apk.outputs.signedReleaseFile}}

    - name: Upload a Build Artifact (Bundle)
      uses: actions/upload-artifact@v3.0.0
      with:
        name: signedBundle
        path: ${{steps.sign_bundle.outputs.signedReleaseFile}}
    
    - name: Compute MD5 hashes for Build Artifact
      run: |
        md5sum ${{steps.sign_apk.outputs.signedReleaseFile}} | awk '{ print $1 }' > ${{steps.sign_apk.outputs.signedReleaseFile}}.md5
        md5sum ${{steps.sign_bundle.outputs.signedReleaseFile}} | awk '{ print $1 }' > ${{steps.sign_bundle.outputs.signedReleaseFile}}.md5

    - name: Upload installer to release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{steps.sign_apk.outputs.signedReleaseFile}}
          ${{steps.sign_apk.outputs.signedReleaseFile}}.md5
          ${{steps.sign_bundle.outputs.signedReleaseFile}}
          ${{steps.sign_bundle.outputs.signedReleaseFile}}.md5
