name: Debug Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
        ./gradlew assembleDebug
        ./gradlew bundleDebug

    - name: Upload a Build Artifact (APK)
      uses: actions/upload-artifact@v3.0.0
      with:
        name: debugAPK
        path: app/build/outputs/apk/debug/*.apk

    - name: Upload a Build Artifact (Bundle)
      uses: actions/upload-artifact@v3.0.0
      with:
        name: debugBundle
        path: app/build/outputs/bundle/debug/*.aab
